image: Visual Studio 2017
version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget.exe restore Seq.App.Azure.DevOps.sln
build:
  project: Seq.App.Azure.DevOps.sln
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: ptZlL/ASI/GaaxHK3ZMWu1W82XPu2gQ7VoDOtrt/JrDSjYqUCvMhNZGM1oUX3Vxb
  on:
    branch: master